<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        // Truncate the table
        DB::table('cities')->truncate();

        // Enable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
$cities = [
    ["name_en" => "Aba Alworood", "name_ar" => "أبا الورود"],
    ["name_en" => "Abayt", "name_ar" => "أبيات"],
    ["name_en" => "Abha", "name_ar" => "أبها"],
    ["name_en" => "Abha Manhal", "name_ar" => "أبها منهل"],
    ["name_en" => "Abiar Al Mashi", "name_ar" => "آبار الماشي"],
    ["name_en" => "Abil", "name_ar" => "أبيل"],
    ["name_en" => "Abu Ajram", "name_ar" => "أبو عجرم"],
    ["name_en" => "Abu Al Arj", "name_ar" => "أبو العرج"],
    ["name_en" => "Abu Arish", "name_ar" => "أبو عريش"],
    ["name_en" => "Abu Arradeef", "name_ar" => "أبو الرديف"],
    ["name_en" => "Abu Dhiba", "name_ar" => "أبو ذيبة"],
    ["name_en" => "Abu Hadriyah", "name_ar" => "أبو حدرية"],
    ["name_en" => "Abu Hajar", "name_ar" => "أبو حجر"],
    ["name_en" => "Abu Muloh", "name_ar" => "أبو ملوح"],
    ["name_en" => "Abu Rakah", "name_ar" => "أبو راكة"],
    ["name_en" => "Abu Rakh", "name_ar" => "أبو رخ"],
    ["name_en" => "Ad Dahinah", "name_ar" => "الضاهنة"],
    ["name_en" => "Ad Dalfaah", "name_ar" => "الضلفة"],
    ["name_en" => "Ad Dilam", "name_ar" => "الدلم"],
    // ["name_en" => "Ad Diriyah", "name_ar" => "الدرعية"],
    ["name_en" => "Ad Dubaiyah", "name_ar" => "الدبيعة"],
    ["name_en" => "Ad Dumayriyah", "name_ar" => "الدمرية"],
    ["name_en" => "Ad Duwadimi", "name_ar" => "الدوادمي"],
    ["name_en" => "Addayer", "name_ar" => "الداير"],
    ["name_en" => "Adham", "name_ar" => "أضم"],
    ["name_en" => "Afif", "name_ar" => "عفيف"],
    ["name_en" => "Afraa", "name_ar" => "عفراء"],
    ["name_en" => "Ahad Al Musarihah", "name_ar" => "أحد المسارحة"],
    ["name_en" => "Ahad Bani Zayd", "name_ar" => "أحد بني زيد"],
    ["name_en" => "Ahad Rifaydah", "name_ar" => "أحد رفيدة"],
    ["name_en" => "Ain Al Nakhal", "name_ar" => "عين النخل"],
    ["name_en" => "Ain Dar", "name_ar" => "عين دار"],
    ["name_en" => "Airj", "name_ar" => "عيرج"],
    ["name_en" => "Al Aarid", "name_ar" => "العارض"],
    ["name_en" => "Al Abar", "name_ar" => "الآبار"],
    ["name_en" => "Al Abyar", "name_ar" => "الأبيار"],
    ["name_en" => "Al Adari", "name_ar" => "العذاري"],
    ["name_en" => "Al Adhiriyah", "name_ar" => "العذرية"],
    ["name_en" => "Al Aflaj (Layla)", "name_ar" => "الأفلاج (ليلى)"],
    ["name_en" => "Al Ahmar", "name_ar" => "الأحمر"],
    ["name_en" => "Al Ahmar-Yanbu", "name_ar" => "الأحمر-ينبع"],
    ["name_en" => "Al Ahsaa", "name_ar" => "الأحساء"],
    ["name_en" => "Al Ais", "name_ar" => "العيس"],
    ["name_en" => "Al Aithmah", "name_ar" => "العيثمة"],
    ["name_en" => "Al Ajfar", "name_ar" => "الأجفر"],
    ["name_en" => "Al Ama ir", "name_ar" => "العمائر"],
    ["name_en" => "Al Amaaria", "name_ar" => "العمارية"],
    ["name_en" => "Al Amajiyah", "name_ar" => "الأمجية"],
    ["name_en" => "Al Amar", "name_ar" => "العمارة"],
    ["name_en" => "Al Amlah", "name_ar" => "الأملة"],
    // ["name_en" => "Al Ammarah", "name_ar" => "العمارة"],
    ["name_en" => "Al Amoah", "name_ar" => "الأمواه"],
    ["name_en" => "AL Andalus", "name_ar" => "الأندلس"],
    ["name_en" => "Al Aqiqah", "name_ar" => "العقيقة"],
    ["name_en" => "Al Aqool", "name_ar" => "العقول"],
    ["name_en" => "Al Aradiyah", "name_ar" => "العريضية"],
    ["name_en" => "Al Araq", "name_ar" => "العرق"],
    ["name_en" => "Al Ardah", "name_ar" => "العرضة"],
    ["name_en" => "Al Ardiyat", "name_ar" => "العريضات"],
    ["name_en" => "Al Arfaa ", "name_ar" => "العرفاء"],
    ["name_en" => "Al Arin", "name_ar" => "العرين"],
    ["name_en" => "Al Arja", "name_ar" => "العرجاء"],
    ["name_en" => "Al Aroos", "name_ar" => "العروس"],
    ["name_en" => "Al Artawi", "name_ar" => "الارتوازي"],
    ["name_en" => "Al Asad", "name_ar" => "الأسد"],
    ["name_en" => "Al Aseelh", "name_ar" => "العسيله"],
    ["name_en" => "Al Ataya", "name_ar" => "العطايا"],
    ["name_en" => "Al Atheeb", "name_ar" => "العتيب"],
    ["name_en" => "Al Atif", "name_ar" => "العطيف"],
    ["name_en" => "Al Awamer", "name_ar" => "العوامر"],
    ["name_en" => "Al Bada", "name_ar" => "البدا"],
    ["name_en" => "Al Badai", "name_ar" => "البدايع"],
    ["name_en" => "Al Badi & Al Qarafi", "name_ar" => "البدي والقرعفي"],
    ["name_en" => "Al Badie Al Shamali ", "name_ar" => "البدي الشمالي"],
    ["name_en" => "Al Baha", "name_ar" => "الباحة"],
    // ["name_en" => "Al Bahah Region", "name_ar" => "منطقة الباحة"],
    ["name_en" => "Al Baheem", "name_ar" => "البهم"],
    ["name_en" => "Al Bashayer", "name_ar" => "البشائر"],
    ["name_en" => "AL BASR", "name_ar" => "البصر"],
    ["name_en" => "Al Batra", "name_ar" => "البتراء"],
    ["name_en" => "Al Bijadyah", "name_ar" => "البجادية"],
    ["name_en" => "Al Bikreyah", "name_ar" => "البكيرية"],
    ["name_en" => "Al Bir", "name_ar" => "البئر"],
    ["name_en" => "Al Birk", "name_ar" => "البرك"],
    // ["name_en" => "Al Bukayriyah", "name_ar" => "البكيرية"],
    ["name_en" => "Al Butayn", "name_ar" => "البطين"],
    ["name_en" => "Al Dalemya", "name_ar" => "الدلمية"],
    ["name_en" => "Al Dhabyah", "name_ar" => "الذابية"],
    ["name_en" => "Al Dhahreyah", "name_ar" => "الظهرية"],
    ["name_en" => "Al Dheelah", "name_ar" => "الذيلة"],
    ["name_en" => "AL DUGHAIMIYAH", "name_ar" => "الضغيمية"],
    ["name_en" => "Al Dulaymiyah", "name_ar" => "الدليمية"],
    ["name_en" => "Al Fagali", "name_ar" => "الفقالي"],
    ["name_en" => "Al Fara", "name_ar" => "الفرا"],
    ["name_en" => "Al Farshah", "name_ar" => "الفرشة"],
    ["name_en" => "Al Fatiha", "name_ar" => "الفتاحة"],
    ["name_en" => "Al Fawwarah", "name_ar" => "الفوارة"],
    ["name_en" => "Al Furaysh", "name_ar" => "الفريش"],
    ["name_en" => "Al Fuwaileq", "name_ar" => "الفويلق"],
    ["name_en" => "Al Gafrat", "name_ar" => "القفرة"],
    ["name_en" => "Al Gamri", "name_ar" => "القمري"],
    ["name_en" => "Al Gandla", "name_ar" => "القندلة"],
    ["name_en" => "Al Gharif ", "name_ar" => "الغريف"],
    ["name_en" => "Al Ghat", "name_ar" => "الغاط"],
    ["name_en" => "Al Habjeia", "name_ar" => "الحبجية"],
    ["name_en" => "Al Haddar", "name_ar" => "الحضر"],
    ["name_en" => "Al Hadror", "name_ar" => "الحضرور"],
    // ["name_en" => "Al Haeer", "name_ar" => "الحائر"],
    ["name_en" => "Al Haith", "name_ar" => "الحيث"],
    ["name_en" => "Al Haqu", "name_ar" => "الحقو"],
    ["name_en" => "Al Harara", "name_ar" => "الحرارة"],
    ["name_en" => "Al Hariq", "name_ar" => "الحريق"],
    ["name_en" => "Al Harth", "name_ar" => "الحارث"],
    ["name_en" => "Al Hayathem", "name_ar" => "الحيثم"],
    ["name_en" => "Al Hayeet", "name_ar" => "الحايت"],
    ["name_en" => "Al Hazim", "name_ar" => "الحازم"],
    ["name_en" => "Al Hazmi", "name_ar" => "الحزمي"],
    ["name_en" => "Al Henayah", "name_ar" => "الحناية"],
    ["name_en" => "Al Heno", "name_ar" => "الحناو"],
    ["name_en" => "Al Hifah", "name_ar" => "الحيفة"],
    ["name_en" => "Al Hijf", "name_ar" => "الحجف"],
    ["name_en" => "Al Hilaliyah", "name_ar" => "الهلالية"],
    ["name_en" => "Al Hinnah", "name_ar" => "الهنة"],
    ["name_en" => "Al huda", "name_ar" => "الهدى"],
    ["name_en" => "Al Hudud Al Shamaliyah", "name_ar" => "الحدود الشمالية"],
    ["name_en" => "Al Hufayr", "name_ar" => "الحفير"],
    ["name_en" => "Al Hufayyirah", "name_ar" => "الحفيرة"],
    ["name_en" => "Al Hufuf", "name_ar" => "الهفوف"],
    ["name_en" => "Al Hulayfah As Sufla", "name_ar" => "الحليفة السفلى"],
    ["name_en" => "Al Hulwah", "name_ar" => "الحلوة"],
    ["name_en" => "Al Husayni", "name_ar" => "الحسيني"],
    ["name_en" => "Al Husayniyah", "name_ar" => "الحسينية"],
    ["name_en" => "Al Husayy", "name_ar" => "الحسي"],
    ["name_en" => "Al Husima", "name_ar" => "الحسيمة"],
    ["name_en" => "Al Huwaya east", "name_ar" => "الحوية الشرقية"],
    ["name_en" => "Al Idabi", "name_ar" => "الإدابي"],
    ["name_en" => "Al JABRIYAH", "name_ar" => "الجابرية"],
    ["name_en" => "Al Jafr", "name_ar" => "الجفر"],
    ["name_en" => "Al Jaradiyah", "name_ar" => "الجرادية"],
    ["name_en" => "Al Jarf", "name_ar" => "الجرف"],
    ["name_en" => "Al Jarn", "name_ar" => "الجرن"],
    // ["name_en" => "Al Jawf Region", "name_ar" => "منطقة الجوف"],
    ["name_en" => "Al Jawwah", "name_ar" => "الجوة"],
    ["name_en" => "Al Jifah", "name_ar" => "الجيفة"],
    ["name_en" => "Al Jishah Al Hofuf", "name_ar" => "الجشة الهفوف"],
    ["name_en" => "Al Jithamiyah", "name_ar" => "الجثمانية"],
    ["name_en" => "Al Jubail", "name_ar" => "الجبيل"],
    ["name_en" => "Al Jubailah", "name_ar" => "الجبيلة"],
    ["name_en" => "Al Jumum", "name_ar" => "الجموم"],
    ["name_en" => "Al kadami", "name_ar" => "الكدامي"],
    ["name_en" => "Al Kadarah", "name_ar" => "القدارة"],
    ["name_en" => "Al Kamil", "name_ar" => "الكامل"],
    ["name_en" => "Al Khafji", "name_ar" => "الخفجي"],
    ["name_en" => "Al Khalaf", "name_ar" => "الخلف"],
    ["name_en" => "Al Khaniq", "name_ar" => "الخانيق"],
    ["name_en" => "Al Kharj", "name_ar" => "الخرج"],
    ["name_en" => "Al Kharkhir", "name_ar" => "الخرخير"],
    ["name_en" => "Al Khashabiyah", "name_ar" => "الخشابية"],
    ["name_en" => "Al Khasiybahi", "name_ar" => "الخصيب"],
    ["name_en" => "Al Khitah", "name_ar" => "الخطة"],
    ["name_en" => "Al khoba", "name_ar" => "الخوبة"],
    ["name_en" => "Al Khubar", "name_ar" => "الخبر"],
    ["name_en" => "Al Khuffiyah", "name_ar" => "الخفية"],
    ["name_en" => "Al khuraybah", "name_ar" => "الخريبة"],
    ["name_en" => "Al Khuraytah", "name_ar" => "الخريطة"],
    ["name_en" => "Al Khurmah", "name_ar" => "الخرمة"],
    ["name_en" => "Al Khushaybi", "name_ar" => "الخشيبي"],
    ["name_en" => "Al Lahien", "name_ar" => "اللحيين"],
    ["name_en" => "Al Laqayit", "name_ar" => "اللقيط"],
    ["name_en" => "Al Lsawiyah", "name_ar" => "اللوية"],
    ["name_en" => "Al Ma`ashabah", "name_ar" => "المعاشبة"],
    ["name_en" => "Al Mada", "name_ar" => "المادى"],
    ["name_en" => "Al Madaya", "name_ar" => "المداية"],
    ["name_en" => "Al Madha", "name_ar" => "المذة"],
    // ["name_en" => "Al Madinah Region", "name_ar" => "منطقة المدينة المنورة"],
    ["name_en" => "AL MAHANI", "name_ar" => "المهاني"],
    ["name_en" => "Al Mahd", "name_ar" => "المهد"],
    ["name_en" => "Al Majardah", "name_ar" => "المجاردة"],
    ["name_en" => "Al Majmaah", "name_ar" => "المجمعة"],
    ["name_en" => "AL MALIDA", "name_ar" => "المالدة"],
    ["name_en" => "Al Marameh", "name_ar" => "المرايم"],
    ["name_en" => "Al Markaz", "name_ar" => "المركز"],
    ["name_en" => "Al Marmuthah", "name_ar" => "المرموقة"],
    ["name_en" => "Al Marooj", "name_ar" => "المروج"],
    ["name_en" => "Al Masgi", "name_ar" => "المصق"],
    ["name_en" => "Al Mayyah", "name_ar" => "المياء"],
    ["name_en" => "Al Midhnab", "name_ar" => "المذنب"],
    ["name_en" => "Al Midrij", "name_ar" => "المضيج"],
    ["name_en" => "Al Mishaliah", "name_ar" => "المشعلية"],
    ["name_en" => "Al Mothalath", "name_ar" => "المثلث"],
    ["name_en" => "Al Mozvin", "name_ar" => "الموزين"],
    ["name_en" => "Al Mubarakah", "name_ar" => "المباركة"],
    ["name_en" => "Al Mudayyih", "name_ar" => "المضيي"],
    ["name_en" => "Al Mukhwah", "name_ar" => "المخواة"],
    ["name_en" => "Al Mulaylih", "name_ar" => "المليليح"],
    ["name_en" => "Al Muntashar", "name_ar" => "المنتشر"],
    ["name_en" => "Al Musayjid", "name_ar" => "المساجد"],
    ["name_en" => "Al Muwaylih", "name_ar" => "المويلح"],
    ["name_en" => "Al Muzahimiyah", "name_ar" => "المزاحمية"],
    ["name_en" => "Al Nabah", "name_ar" => "النباة"],
    ["name_en" => "Al Nuzha", "name_ar" => "النزهة"],
    ["name_en" => "Al Ogam", "name_ar" => "العقم"],
    ["name_en" => "Al Qaa", "name_ar" => "القاع"],
    ["name_en" => "Al Qaid", "name_ar" => "القيد"],
    ["name_en" => "Al Qaied", "name_ar" => "القائد"],
    ["name_en" => "Al Qari", "name_ar" => "القاري"],
    ["name_en" => "Al Qarin", "name_ar" => "القارين"],
    ["name_en" => "Al Qarinah", "name_ar" => "القرينة"],
    // ["name_en" => "Al Qassim Region", "name_ar" => "منطقة القصيم"],
    ["name_en" => "Al Qatif", "name_ar" => "القطيف"],
    ["name_en" => "Al Qeddeh", "name_ar" => "القدة"],
    ["name_en" => "Al Qirawan", "name_ar" => "القرعوان"],
    ["name_en" => "Al qowarah", "name_ar" => "القوارة"],
    ["name_en" => "Al Qulayyib", "name_ar" => "القليب"],
    ["name_en" => "Al Qunfidhah", "name_ar" => "القنفذة"],
    // ["name_en" => "Al Qurainah", "name_ar" => "القرينة"],
    ["name_en" => "Al Qurayyat", "name_ar" => "القريات"],
    ["name_en" => "AL QURESHIYAT", "name_ar" => "القريشيات"],
    // ["name_en" => "Al Rafaeya'a", "name_ar" => "الرفيعة"],
    ["name_en" => "Al Rafaie", "name_ar" => "الرفاعي"],
    ["name_en" => "Al Rathaya", "name_ar" => "الرثايا"],
    ["name_en" => "Al Rayis", "name_ar" => "الريس"],
    ["name_en" => "Al Reeth", "name_ar" => "الريث"],
    ["name_en" => "Al Ruqi", "name_ar" => "الرقي"],
    ["name_en" => "Al Sahalil", "name_ar" => "السحليل"],
    ["name_en" => "Al Salamah", "name_ar" => "السلامة"],
    ["name_en" => "AL SAYL ALKHABIR", "name_ar" => "السيل الكبير"],
    ["name_en" => "AL SAYL ALSAGHIR", "name_ar" => "السيل الصغير"],
    ["name_en" => "Al Shatt", "name_ar" => "الشط"],
    ["name_en" => "Al Shegrah", "name_ar" => "الشغراء"],
    ["name_en" => "Al Shehiyah", "name_ar" => "الشحية"],
    ["name_en" => "Al Sheqiqah", "name_ar" => "الشقيقة"],
    ["name_en" => "Al Shlayil", "name_ar" => "الشليل"],
    ["name_en" => "Al Shoqiyah", "name_ar" => "الشوقية"],
    ["name_en" => "Al Shuaba", "name_ar" => "الشعبة"],
    ["name_en" => "Al Sih", "name_ar" => "السيح"],
    ["name_en" => "Al Subaykhah", "name_ar" => "الصبيخة"],
    ["name_en" => "Al Sulaimi", "name_ar" => "السليمي"],
    ["name_en" => "Al tanumah al Qassim", "name_ar" => "التنومة القصيم"],
    ["name_en" => "Al Taraf", "name_ar" => "الطرف"],
    ["name_en" => "Al Theniah", "name_ar" => "الثنية"],
    ["name_en" => "Al Torkiyah", "name_ar" => "التركية"],
    ["name_en" => "Al Twaitheer", "name_ar" => "التويثير"],
    ["name_en" => "Al Udayd", "name_ar" => "العيديد"],
    ["name_en" => "Al Uferiah", "name_ar" => "العفارية"],
    ["name_en" => "Al Umrah Al Jadidah", "name_ar" => "العمره الجديدة"],
    ["name_en" => "Al Uwayqilah", "name_ar" => "العويقيلة"],
    ["name_en" => "Al Wajh", "name_ar" => "الوجه"],
    ["name_en" => "Al Wannan", "name_ar" => "الونان"],
    ["name_en" => "Al Wasayta", "name_ar" => "الوسيطى"],
    ["name_en" => "Al-Batna", "name_ar" => "البطنة"],
    ["name_en" => "Al-Faqarah", "name_ar" => "الفقارة"],
    ["name_en" => "Al-halaa", "name_ar" => "الحلا"],
    ["name_en" => "AL-JUAYMAH", "name_ar" => "الجويمة"],
    ["name_en" => "Al-Matan", "name_ar" => "المطاعن"],
    ["name_en" => "Al-MNSALA", "name_ar" => "المصلاة"],
    ["name_en" => "Al-Nasifa", "name_ar" => "النصيفة"],
    ["name_en" => "Al-Umran", "name_ar" => "العمران"],
    ["name_en" => "Al-Wozeyh", "name_ar" => "العويذة"],
    ["name_en" => "Alabadilah", "name_ar" => "العبادلة"],
    ["name_en" => "Alaraysah Al Janubi Subdivision", "name_ar" => "العرائس الجنوبية"],
    ["name_en" => "Alaraysah Ash Shamali Subdivision", "name_ar" => "العرائس الشمالية"],
    ["name_en" => "Alarjeen", "name_ar" => "العارجين"],
    ["name_en" => "Alasilan", "name_ar" => "العصلان"],
    // ["name_en" => "Alearduh", "name_ar" => "العرضة"],
    // ["name_en" => "Algayed", "name_ar" => "القائد"],
    ["name_en" => "Alhada", "name_ar" => "الهداء"],
    ["name_en" => "Alhayma", "name_ar" => "الحيمة"],
    ["name_en" => "AlJanadria", "name_ar" => "الجنادرية"],
    ["name_en" => "Aljurbah", "name_ar" => "الجربة"],
    ["name_en" => "Alkhazzan", "name_ar" => "الخزان"],
    ["name_en" => "AlKhhafah", "name_ar" => "الخفاء"],
    ["name_en" => "Almazef", "name_ar" => "المزيف"],
    ["name_en" => "Almutayrifi", "name_ar" => "المطيرفي"],
    ["name_en" => "Almuzayri", "name_ar" => "المزيري"],
    ["name_en" => "Alnabhanya", "name_ar" => "النبهانية"],
    ["name_en" => "Alqabil", "name_ar" => "القبل"],
    ["name_en" => "Alquaba", "name_ar" => "القعابا"],
    ["name_en" => "AlQudaih", "name_ar" => "القديح"],
    ["name_en" => "Alqurra", "name_ar" => "القرعاء"],
    ["name_en" => "Alsawarimah", "name_ar" => "الصوارمة"],
    ["name_en" => "Alshahili", "name_ar" => "الشاهلي"],
    // ["name_en" => "Alshihyah", "name_ar" => "الشحية"],
    ["name_en" => "Alshuqayri", "name_ar" => "الشقيري"],
    ["name_en" => "Alshwaaq", "name_ar" => "الشواق"],
    ["name_en" => "Alsilaa", "name_ar" => "السلعة"],
    ["name_en" => "Alsulmania", "name_ar" => "السليمانية"],
    ["name_en" => "Alturfiyah", "name_ar" => "الطرفية"],
    ["name_en" => "Alwasqah", "name_ar" => "الوصفة"],
    ["name_en" => "Alyutamah", "name_ar" => "اليتمة"],
    ["name_en" => "Amaaer Ben Sana'a", "name_ar" => "عمائر بن صنعاء"],
    ["name_en" => "Amaq", "name_ar" => "عماق"],
    ["name_en" => "An Nabiyah", "name_ar" => "النابية"],
    ["name_en" => "An Nabk Abu Qasr", "name_ar" => "النابك ابو قصر"],
    ["name_en" => "An nabqiyyah", "name_ar" => "النبيقية"],
    ["name_en" => "An Nafiah", "name_ar" => "النفيعة"],
    ["name_en" => "An Nasiriyah", "name_ar" => "الناصرية"],
    ["name_en" => "An Nawwariyyah", "name_ar" => "النوارية"],
    ["name_en" => "An Nazayim", "name_ar" => "النظيم"],
    ["name_en" => "An Nuayriyah", "name_ar" => "النعيرية"],
    ["name_en" => "An Nuqrah", "name_ar" => "النقرة"],
    ["name_en" => "Aqiq", "name_ar" => "العقيق"],
    ["name_en" => "Ar Radifah", "name_ar" => "الرديفة"],
    // ["name_en" => "Ar Rafi'ah", "name_ar" => "الرفيعة"],
    ["name_en" => "Ar Rafiah", "name_ar" => "الرفيعة"],
    ["name_en" => "Ar Rass", "name_ar" => "الرس"],
    ["name_en" => "Ar Rawdah ", "name_ar" => "الروضة"],
    ["name_en" => "Ar Rayn", "name_ar" => "الرين"],
    ["name_en" => "Ar Rishawiyah", "name_ar" => "الرشاوية"],
    ["name_en" => "Arafa", "name_ar" => "عرفة"],
    ["name_en" => "Arar", "name_ar" => "عرعر"],
    ["name_en" => "Artawiah", "name_ar" => "الأرطاوية"],
    ["name_en" => "As Sahwah", "name_ar" => "السحوة"],
    ["name_en" => "As Salhiyah", "name_ar" => "الصالحية"],
    ["name_en" => "As Sam'uriyah", "name_ar" => "السميرية"],
    ["name_en" => "As Shamli", "name_ar" => "الشملي"],
    ["name_en" => "As Sihaf", "name_ar" => "الصحاف"],
    // ["name_en" => "As Sulaimaniyah", "name_ar" => "السليمانية"],
    ["name_en" => "As Sulayyil", "name_ar" => "السليل"],
    ["name_en" => "As Sulubiayh", "name_ar" => "الصلبية"],
    ["name_en" => "Asbtar", "name_ar" => "أسبطر"],
    ["name_en" => "Asfan", "name_ar" => "أصيفان"],
    ["name_en" => "Ash Shaara", "name_ar" => "الشعرا"],
    ["name_en" => "Ash Shananah", "name_ar" => "الشنانة"],
    ["name_en" => "Ash Shimasiyah", "name_ar" => "الشماسية"],
    ["name_en" => "Ash Shinan", "name_ar" => "الشنان"],
    ["name_en" => "Ash Shumaysi", "name_ar" => "الشماسي"],
    ["name_en" => "Ash Shuqaiq", "name_ar" => "الشقيق"],
    // ["name_en" => "Ash Shuqrah", "name_ar" => "الشقراء"],
    ["name_en" => "Asheerah Sudayer", "name_ar" => "الشيرة سدير"],
    ["name_en" => "Asir", "name_ar" => "عسير"],
    // ["name_en" => "Asir Region", "name_ar" => "منطقة عسير"],
    ["name_en" => "Assadawi", "name_ar" => "الأسدوي"],
    ["name_en" => "Assalmanyah", "name_ar" => "السلامانية"],
    ["name_en" => "Assiyah", "name_ar" => "عسيا"],
    ["name_en" => "Asuwayq", "name_ar" => "السويق"],
    ["name_en" => "At Tan'Im", "name_ar" => "التنعيم"],
    ["name_en" => "At Tiraq", "name_ar" => "الطريق"],
    ["name_en" => "At Tuwal", "name_ar" => "التوال"],
    ["name_en" => "At Tuwayr", "name_ar" => "التوير"],
    ["name_en" => "Atawleh", "name_ar" => "التاولة"],
    ["name_en" => "Ath Thamiriyah", "name_ar" => "الثامرية"],
    ["name_en" => "Ath Thybiyah", "name_ar" => "الطبيعية"],
    ["name_en" => "Awamiah", "name_ar" => "العوامية"],
    ["name_en" => "Awdah Sudayer", "name_ar" => "عودة سدير"],
    ["name_en" => "Ayn Fuhayd", "name_ar" => "عين فهيد"],
    ["name_en" => "Az Zughayn", "name_ar" => "الزغين"],
    ["name_en" => "Az Zulfi", "name_ar" => "الزلفي"],
    ["name_en" => "Bada", "name_ar" => "بدا"],
    ["name_en" => "Badar Hunain", "name_ar" => "بدر حنين"],
    ["name_en" => "Badr", "name_ar" => "بدر"],
    ["name_en" => "Badr Al Janoub", "name_ar" => "بدر الجنوب"],
    ["name_en" => "Bahara", "name_ar" => "بحرة"],
    ["name_en" => "Bahr Abu Sukaynah", "name_ar" => "بحر ابو سكينة"],
    ["name_en" => "Bahrain Causeway", "name_ar" => "جسر البحرين"],
    ["name_en" => "Bahrat Al Moujoud", "name_ar" => "بحرة الموجود"],
    ["name_en" => "Balahmar", "name_ar" => "بلحمر"],
    ["name_en" => "Baljurashi", "name_ar" => "بلجرشي"],
    ["name_en" => "Balqarn", "name_ar" => "بلقرن"],
    ["name_en" => "Banban", "name_ar" => "بنبان"],
    ["name_en" => "Bani Hamim", "name_ar" => "بني حميم"],
    ["name_en" => "Bani Hasan", "name_ar" => "بني حسن"],
    ["name_en" => "Bani Malek", "name_ar" => "بني مالك"],
    ["name_en" => "Baqa Ash Sharqiyah", "name_ar" => "بقاء الشرقية"],
    ["name_en" => "Baqaa", "name_ar" => "بقاء"],
    ["name_en" => "Bareq", "name_ar" => "بارق"],
    ["name_en" => "Batha", "name_ar" => "البطحاء"],
    ["name_en" => "Bawathil", "name_ar" => "بواثيل"],
    ["name_en" => "Baynah", "name_ar" => "بينة"],
    ["name_en" => "Baysh", "name_ar" => "بيش"],
    ["name_en" => "Billasmar", "name_ar" => "بلسمر"],
    ["name_en" => "Bin Aqeel Palace", "name_ar" => "قصر بن عقيل"],
    ["name_en" => "Bir Bin Harmas", "name_ar" => "بئر بن هرماس"],
    ["name_en" => "Birk", "name_ar" => "برك"],
    ["name_en" => "Bishah", "name_ar" => "بيشة"],
    ["name_en" => "Buni Eisaa", "name_ar" => "بني عيسى"],
    ["name_en" => "Buqayq", "name_ar" => "بقيق"],
    ["name_en" => "Buraydah", "name_ar" => "بريدة"],
    ["name_en" => "Daelim", "name_ar" => "الديلم"],
    ["name_en" => "Dahu", "name_ar" => "دهو"],
    ["name_en" => "Damad", "name_ar" => "ضمد"],
    ["name_en" => "Dammam", "name_ar" => "الدمام"],
    ["name_en" => "Darb", "name_ar" => "الدرب"],
    ["name_en" => "Dariyah", "name_ar" => "الدرعية"],
    ["name_en" => "Dawmat Al Jandal", "name_ar" => "دومة الجندل"],
    ["name_en" => "dayida", "name_ar" => "الدائد"],
    ["name_en" => "Deleted", "name_ar" => "محذوف"],
    ["name_en" => "Deraab", "name_ar" => "ديراب"],
    ["name_en" => "Dhahban", "name_ar" => "ذهبان"],
    ["name_en" => "Dhahran", "name_ar" => "الظهران"],
    ["name_en" => "Dhahran Al Janoub", "name_ar" => "الظهران الجنوب"],
    ["name_en" => "DHALAM", "name_ar" => "ظلم"],
    ["name_en" => "Dhurma", "name_ar" => "ضرما"],
    ["name_en" => "Duba", "name_ar" => "ضبا"],
    ["name_en" => "DUBAY'AH", "name_ar" => "ضبيعة"],
    ["name_en" => "Duhknah", "name_ar" => "ضحكنه"],
    ["name_en" => "Dulay Rashid", "name_ar" => "ضلي رشيد"],
    ["name_en" => "Dulayhan", "name_ar" => "ضليحان"],
    ["name_en" => "dummy", "name_ar" => "نموذج"],
    ["name_en" => "Eaqabat shiear", "name_ar" => "عقبة شعار"],
    ["name_en" => "Eastern Province", "name_ar" => "المنطقة الشرقية"],
    // ["name_en" => "Eastern Region", "name_ar" => "المنطقة الشرقية"],
    ["name_en" => "Eayan dar aljadida", "name_ar" => "عيان دار الجديدة"],
    ["name_en" => "Eayan dar alqadima", "name_ar" => "عيان دار القديمة"],
    ["name_en" => "Edadh", "name_ar" => "اداد"],
    ["name_en" => "Either", "name_ar" => "ايثير"],
    ["name_en" => "El-Ebva", "name_ar" => "الأبوة"],
    ["name_en" => "Eshirah", "name_ar" => "العشيرة"],
    ["name_en" => "faihiq", "name_ar" => "فهيق"],
    ["name_en" => "Farasan", "name_ar" => "فرسان"],
    ["name_en" => "Fawada", "name_ar" => "فواده"],
    ["name_en" => "Fayd", "name_ar" => "فيد"],
    ["name_en" => "Fayfa", "name_ar" => "فيفا"],
    ["name_en" => "Feyadh Tabrjal", "name_ar" => "فيض تبرجل"],
    ["name_en" => "free", "name_ar" => "حر"],
    ["name_en" => "Gaabah", "name_ar" => "قعبة"],
    ["name_en" => "Gaha", "name_ar" => "جحة"],
    ["name_en" => "Gayal", "name_ar" => "جيال"],
    ["name_en" => "Ghaf Al Jawa", "name_ar" => "غف الجوى"],
    ["name_en" => "Ghamid Al Zhinad", "name_ar" => "غامد الزناد"],
    ["name_en" => "Ghanwa", "name_ar" => "غنوة"],
    ["name_en" => "Ghazalah", "name_ar" => "غزالة"],
    ["name_en" => "Ghizlan", "name_ar" => "غزلان"],
    ["name_en" => "Ghran", "name_ar" => "غران"],
    ["name_en" => "Ghtai", "name_ar" => "غطي"],
    ["name_en" => "Ghubairah", "name_ar" => "غبيرة"],
    ["name_en" => "Gilwa", "name_ar" => "قلوة"],
    ["name_en" => "habeel", "name_ar" => "حبل"],
    ["name_en" => "HADAA", "name_ar" => "هداء"],
    ["name_en" => "Hadban", "name_ar" => "حدبان"],
    ["name_en" => "HADCO-Almarai", "name_ar" => "هتكوا-المراعي"],
    ["name_en" => "Haddadah", "name_ar" => "حدادة"],
    ["name_en" => "Haddat ash Sham", "name_ar" => "حدث الشام"],
    ["name_en" => "Hadeethah", "name_ar" => "حديثة"],
    ["name_en" => "Hafar Al Batin", "name_ar" => "حفر الباطن"],
    ["name_en" => "Hail", "name_ar" => "حائل"],
    // ["name_en" => "Hail Region", "name_ar" => "منطقة حائل"],
    ["name_en" => "Hajrah", "name_ar" => "حجرة"],
    ["name_en" => "Halat Ammar", "name_ar" => "حالة عمار"],
    ["name_en" => "Hali", "name_ar" => "حلي"],
    ["name_en" => "Hamid", "name_ar" => "حامد"],
    ["name_en" => "Hanidh", "name_ar" => "حنيذ"],
    ["name_en" => "Haqil", "name_ar" => "حقل"],
    ["name_en" => "Harad", "name_ar" => "حراد"],
    ["name_en" => "Harajah", "name_ar" => "حرجة"],
    // ["name_en" => "Harajah eastern region", "name_ar" => "حرجة المنطقة الشرقية"],
    ["name_en" => "Harmah", "name_ar" => "حرمة"],
    ["name_en" => "Harub", "name_ar" => "حروب"],
    ["name_en" => "Hawalli", "name_ar" => "حولي"],
    ["name_en" => "Hawea/Taif", "name_ar" => "حوية/الطائف"],
    ["name_en" => "Haweyah", "name_ar" => "حوية"],
    ["name_en" => "Hawtat Bani Tamim", "name_ar" => "حوطة بني تميم"],
    ["name_en" => "Hawtat Sudayr", "name_ar" => "حوطة سدير"],
    ["name_en" => "Hayer", "name_ar" => "الحائر"],
    ["name_en" => "Hazm Al Jalamid", "name_ar" => "حزم الجلاميد"],
    ["name_en" => "Hedeb", "name_ar" => "حديب"],
    ["name_en" => "Hinakeya", "name_ar" => "الحناكية"],
    ["name_en" => "Hubuna", "name_ar" => "حبونا"],
    ["name_en" => "Hullatal Ahwass", "name_ar" => "حلة الاحواز"],
    ["name_en" => "Hunaydhl", "name_ar" => "حنيدل"],
    ["name_en" => "Huraymila", "name_ar" => "حريملاء"],
    ["name_en" => "hyt", "name_ar" => "حيط"],
    ["name_en" => "Inak", "name_ar" => "عنك"],
    ["name_en" => "Iskan city", "name_ar" => "إسكان المدينة"],
    ["name_en" => "Ithrah", "name_ar" => "إثراء"],
    // ["name_en" => "Ja'Araneh", "name_ar" => "جعرة"],
    ["name_en" => "Jaaraneh", "name_ar" => "جعرة"],
    ["name_en" => "Jalajel", "name_ar" => "جلجل"],
    ["name_en" => "Jamajm", "name_ar" => "جماجم"],
    ["name_en" => "Jash", "name_ar" => "جاش"],
    ["name_en" => "Jazan", "name_ar" => "جازان"],
    // ["name_en" => "Jazan Region", "name_ar" => "منطقة جازان"],
    ["name_en" => "Jeddah", "name_ar" => "جدة"],
    ["name_en" => "Jefin", "name_ar" => "جفين"],
    ["name_en" => "Jibal Khuraibah", "name_ar" => "جبال خريبة"],
    ["name_en" => "Jilah", "name_ar" => "جله"],
    ["name_en" => "Jouf", "name_ar" => "الجوف"],
    ["name_en" => "Juatha", "name_ar" => "جواثا"],
    ["name_en" => "Jubbah", "name_ar" => "جبة"],
    ["name_en" => "Jubrah", "name_ar" => "جبرة"],
    // ["name_en" => "Judah", "name_ar" => "جدة"],
    ["name_en" => "Julayjilah", "name_ar" => "جليجله"],
    ["name_en" => "Kahlah", "name_ar" => "كحلة"],
    ["name_en" => "Kara", "name_ar" => "كرا"],
    // ["name_en" => "Kara'A", "name_ar" => "كرا"],
    ["name_en" => "Karboos", "name_ar" => "كربوس"],
    ["name_en" => "KAUST", "name_ar" => "كاوست"],
    ["name_en" => "Khabash", "name_ar" => "خباش"],
    ["name_en" => "Khaiber Al-Janoub", "name_ar" => "خيبر الجنوب"],
    ["name_en" => "Khairan", "name_ar" => "خيران"],
    ["name_en" => "Khamasin", "name_ar" => "خماسين"],
    ["name_en" => "Khamis Mushayt", "name_ar" => "خميس مشيط"],
    ["name_en" => "Khasawyah", "name_ar" => "خساوية"],
    ["name_en" => "Khaybar", "name_ar" => "خيبر"],
    // ["name_en" => "Khbash", "name_ar" => "خباش"],
    ["name_en" => "Khodaria", "name_ar" => "خضيرية"],
    ["name_en" => "Khudayra", "name_ar" => "خضيرة"],
    ["name_en" => "Khulais", "name_ar" => "خليص"],
    ["name_en" => "Khursaniyah", "name_ar" => "خرسانية"],
    ["name_en" => "King Abdullah Economic City", "name_ar" => "مدينة الملك عبدالله الاقتصادية"],
    ["name_en" => "King Khalid Military City", "name_ar" => "مدينة الملك خالد العسكرية"],
    ["name_en" => "Kouba", "name_ar" => "كوبا"],
    ["name_en" => "Kubadah", "name_ar" => "كبادة"],
    ["name_en" => "Lahumah", "name_ar" => "لحمة"],
    ["name_en" => "Laith", "name_ar" => "الليث"],
    ["name_en" => "Layla", "name_ar" => "ليلى"],
    ["name_en" => "Madinah", "name_ar" => "المدينة المنورة"],
    ["name_en" => "Madrakah", "name_ar" => "مدركة"],
    ["name_en" => "Mahalah", "name_ar" => "محلة"],
    ["name_en" => "Mahd Al Dahab", "name_ar" => "مهد الذهب"],
    ["name_en" => "Makkah", "name_ar" => "مكة"],
    // ["name_en" => "Makkah Region", "name_ar" => "منطقة مكة"],
    ["name_en" => "Malham", "name_ar" => "ملهم"],
    ["name_en" => "Mandak", "name_ar" => "مندك"],
    ["name_en" => "Manifah", "name_ar" => "منيفة"],
    ["name_en" => "Mansak", "name_ar" => "منسك"],
    ["name_en" => "Marabah", "name_ar" => "مربحة"],
    ["name_en" => "Maraghan", "name_ar" => "مرغان"],
    ["name_en" => "Marat", "name_ar" => "مرات"],
    ["name_en" => "Mastura", "name_ar" => "مستورة"],
    ["name_en" => "Mawqaq", "name_ar" => "موقق"],
    ["name_en" => "Maysaan", "name_ar" => "ميسان"],
    ["name_en" => "Mehr Bisha Center", "name_ar" => "مركز مهر بيشة"],
    ["name_en" => "Mektaa", "name_ar" => "مقطع"],
    ["name_en" => "Mighati", "name_ar" => "مغطى"],
    ["name_en" => "Military City", "name_ar" => "المدينة العسكرية"],
    ["name_en" => "Mindassah", "name_ar" => "مندسة"],
    ["name_en" => "Minwa", "name_ar" => "منوى"],
    ["name_en" => "Mishalah", "name_ar" => "مشالح"],
    ["name_en" => "Mizhirah", "name_ar" => "مزاهرة"],
    // ["name_en" => "Moqaq", "name_ar" => "موقق"],
    ["name_en" => "Mubaraz", "name_ar" => "المبرز"],
    ["name_en" => "Mubayid", "name_ar" => "مبيد"],
    ["name_en" => "Mubhel", "name_ar" => "مبهل"],
    ["name_en" => "Mudhaylif", "name_ar" => "المظيلف"],
    ["name_en" => "Muhayil Aseer", "name_ar" => "محايل عسير"],
    ["name_en" => "Mulaija", "name_ar" => "مليجة"],
    ["name_en" => "Mulayh", "name_ar" => "ملحي"],
    ["name_en" => "Munifat Al Qaid", "name_ar" => "منيفة القائد"],
    ["name_en" => "Muwayh", "name_ar" => "المويه"],
    ["name_en" => "Na`am", "name_ar" => "نعم"],
    ["name_en" => "Nabiya", "name_ar" => "نابية"],
    ["name_en" => "Najran", "name_ar" => "نجران"],
    // ["name_en" => "Najran Region", "name_ar" => "منطقة نجران"],
    ["name_en" => "Nakeea", "name_ar" => "نقيع"],
    ["name_en" => "Namas", "name_ar" => "النماص"],
    ["name_en" => "Nawan", "name_ar" => "نوا"],
    ["name_en" => "Neom", "name_ar" => "نيوم"],
    ["name_en" => "Nimra", "name_ar" => "نمره"],
    ["name_en" => "Nimran", "name_ar" => "نمران"],
    ["name_en" => "Nisab", "name_ar" => "نصاب"],
    ["name_en" => "Nita", "name_ar" => "نيتا"],
    ["name_en" => "Nkheelan", "name_ar" => "النخيلان"],
    // ["name_en" => "Northern Borders", "name_ar" => "الحدود الشمالية"],
    ["name_en" => "Nubayha", "name_ar" => "نبيهة"],
    ["name_en" => "Nwariah", "name_ar" => "نوارية"],
    ["name_en" => "Ojam", "name_ar" => "أوجم"],
    ["name_en" => "Oula", "name_ar" => "أولى"],
    ["name_en" => "Oyaynah", "name_ar" => "عيينة"],
    ["name_en" => "Qahmah", "name_ar" => "القحمة"],
    // ["name_en" => "Qana", "name_ar" => "قنا"],
    ["name_en" => "Qarah", "name_ar" => "قرح"],
    ["name_en" => "Qaryat Al Ulya", "name_ar" => "قرية العليا"],
    ["name_en" => "Qasab", "name_ar" => "قسب"],
    ["name_en" => "Qasab-Aseer", "name_ar" => "قسب عسير"],
    ["name_en" => "Qassim", "name_ar" => "القصيم"],
    ["name_en" => "Qaysumah", "name_ar" => "القيصومة"],
    ["name_en" => "Qbah", "name_ar" => "قباء"],
    ["name_en" => "Qia", "name_ar" => "قيا"],
    // ["name_en" => "Qina", "name_ar" => "قنا"],
    ["name_en" => "Qouz", "name_ar" => "قوز"],
    ["name_en" => "Quai", "name_ar" => "قوا"],
    ["name_en" => "Qufar", "name_ar" => "قفر"],
    ["name_en" => "Qusayba", "name_ar" => "قصيبة"],
    ["name_en" => "Qusor almoqbel", "name_ar" => "قصور المقبل"],
    ["name_en" => "Quwayiyah", "name_ar" => "القويعية"],
    ["name_en" => "Rabigh", "name_ar" => "رابغ"],
    ["name_en" => "RADHWAN", "name_ar" => "رضوان"],
    ["name_en" => "Rafha", "name_ar" => "رفحاء"],
    ["name_en" => "Rahima", "name_ar" => "رحيمة"],
    ["name_en" => "Rania", "name_ar" => "رنية"],
    ["name_en" => "Ras Al Kheir", "name_ar" => "رأس الخير"],
    ["name_en" => "Ras Baridi", "name_ar" => "رأس بريدي"],
    ["name_en" => "Ras Tannurah", "name_ar" => "رأس تنورة"],
    ["name_en" => "Rawdat Al Hisu", "name_ar" => "روضة الحسو"],
    ["name_en" => "Rawdat Habbas", "name_ar" => "روضة حاباس"],
    ["name_en" => "Remah", "name_ar" => "رماح"],
    ["name_en" => "Rijal Almaa", "name_ar" => "رجال المع"],
    ["name_en" => "Riyad Al Khabra", "name_ar" => "رياض الخبراء"],
    ["name_en" => "Riyadh", "name_ar" => "الرياض"],
    // ["name_en" => "Riyadh Region", "name_ar" => "منطقة الرياض"],
    ["name_en" => "Rowdat Sodair", "name_ar" => "روضة سدير"],
    ["name_en" => "Rughabah", "name_ar" => "رغبة"],
    ["name_en" => "Ruqayqah", "name_ar" => "رقائق"],
    ["name_en" => "Rvaya Aljamsh", "name_ar" => "رواية الجميش"],
    ["name_en" => "Rwaydah", "name_ar" => "رويدة"],
    ["name_en" => "Sabhat", "name_ar" => "سبحت"],
    ["name_en" => "Sabkah", "name_ar" => "سبخة"],
    ["name_en" => "Sabt Aljarah", "name_ar" => "سبت الجارة"],
    ["name_en" => "Sabt El Alaya", "name_ar" => "سبت العلايا"],
    ["name_en" => "Sabya", "name_ar" => "صبيا"],
    ["name_en" => "Sadal Malik", "name_ar" => "سد الملك"],
    ["name_en" => "Sadus", "name_ar" => "سدوس"],
    ["name_en" => "Sadyan", "name_ar" => "صديان"],
    ["name_en" => "Saeedat Alswaleha", "name_ar" => "سيدة الصويلحة"],
    ["name_en" => "Safanyah", "name_ar" => "صفانيا"],
    ["name_en" => "Safwa", "name_ar" => "صفوى"],
    ["name_en" => "Sahna", "name_ar" => "سحناء"],
    ["name_en" => "Sajir", "name_ar" => "ساجر"],
    ["name_en" => "Sakaka", "name_ar" => "سكاكا"],
    ["name_en" => "Salasil", "name_ar" => "سلاسل"],
    ["name_en" => "Salbookh", "name_ar" => "صلبوخ"],
    ["name_en" => "Salwa", "name_ar" => "سلوى"],
    ["name_en" => "Samakh", "name_ar" => "سماخ"],
    ["name_en" => "Sammed", "name_ar" => "سمد"],
    ["name_en" => "Samrat Al Jed", "name_ar" => "سمرة الجيد"],
    ["name_en" => "Samtah", "name_ar" => "صامطة"],
    ["name_en" => "Saqf", "name_ar" => "سقف"],
    ["name_en" => "Sarar", "name_ar" => "صرار"],
    ["name_en" => "Sarat Obeida", "name_ar" => "سراة عبيدة"],
    ["name_en" => "Satorp", "name_ar" => "ساتورب"],
    ["name_en" => "Sayhat", "name_ar" => "سيهات"],
    ["name_en" => "Sayirah", "name_ar" => "سيرة"],
    ["name_en" => "Selselah", "name_ar" => "سلسلة"],
    ["name_en" => "Shaqra", "name_ar" => "شقراء"],
    ["name_en" => "Shari", "name_ar" => "شاري"],
    ["name_en" => "Sharmaa", "name_ar" => "شرما"],
    ["name_en" => "Sharurah", "name_ar" => "شرورة"],
    ["name_en" => "Shaybah", "name_ar" => "شيبة"],
    ["name_en" => "Shedgum", "name_ar" => "شدقم"],
    ["name_en" => "Shefa", "name_ar" => "الشفا"],
    ["name_en" => "Shefa'a", "name_ar" => "الشفاء"],
    // ["name_en" => "Sheqra", "name_ar" => "شقراء"],
    ["name_en" => "Shifiyah", "name_ar" => "شفيعية"],
    ["name_en" => "Shoaiba", "name_ar" => "الشعيبة"],
    ["name_en" => "Shoqsan", "name_ar" => "شقصان"],
    ["name_en" => "Shraiee", "name_ar" => "شريعة"],
    ["name_en" => "Shubaytah", "name_ar" => "شبيطة"],
    ["name_en" => "Shumeisi", "name_ar" => "شماسي"],
    ["name_en" => "Siir", "name_ar" => "سير"],
    ["name_en" => "Sil xxQiyalxx", "name_ar" => "سيل"],
    ["name_en" => "Simira", "name_ar" => "سميرا"],
    ["name_en" => "Subaih", "name_ar" => "صبيح"],
    ["name_en" => "Subheka", "name_ar" => "صبحكة"],
    ["name_en" => "Sudayer", "name_ar" => "سدير"],
    ["name_en" => "Sunbah", "name_ar" => "صنبة"],
    ["name_en" => "Suwaidhrah", "name_ar" => "سويدره"],
    ["name_en" => "Suwayr", "name_ar" => "سوير"],
    ["name_en" => "Tabalah", "name_ar" => "تبالة"],
    ["name_en" => "Tabashah", "name_ar" => "تباشه"],
    ["name_en" => "Tablah", "name_ar" => "تبل"],
    ["name_en" => "Tabrjal", "name_ar" => "طبرجل"],
    ["name_en" => "Tabuk", "name_ar" => "تبوك"],
    // ["name_en" => "Tabuk Region", "name_ar" => "منطقة تبوك"],
    ["name_en" => "Taiba", "name_ar" => "طيبة"],
    ["name_en" => "Taif", "name_ar" => "الطائف"],
    ["name_en" => "Tamniah", "name_ar" => "تمنية"],
    ["name_en" => "Tanajib", "name_ar" => "تناجيب"],
    ["name_en" => "Tanumah", "name_ar" => "تنومة"],
    ["name_en" => "tarif qassim", "name_ar" => "طرف القصيم"],
    ["name_en" => "Tarut", "name_ar" => "تاروت"],
    ["name_en" => "Tathilith", "name_ar" => "تثليث"],
    ["name_en" => "Tayma", "name_ar" => "تيماء"],
    ["name_en" => "Tebrak", "name_ar" => "تبراك"],
    ["name_en" => "Temeriyah", "name_ar" => "تمرية"],
    ["name_en" => "Tendaha", "name_ar" => "تندحة"],
    ["name_en" => "Thabya", "name_ar" => "ثابية"],
    // ["name_en" => "Thadij", "name_ar" => "ثادق"],
    ["name_en" => "Thadiq", "name_ar" => "ثادق"],
    ["name_en" => "Thaj", "name_ar" => "ثاج"],
    ["name_en" => "Thar", "name_ar" => "ثار"],
    ["name_en" => "Tharmada", "name_ar" => "ثرمدا"],
    ["name_en" => "Thebea", "name_ar" => "الذيباء"],
    ["name_en" => "Thuqba", "name_ar" => "ثقبة"],
    ["name_en" => "Thurayban", "name_ar" => "ثريبان"],
    ["name_en" => "Thuwal", "name_ar" => "ثول"],
    ["name_en" => "Tumair", "name_ar" => "تمير"],
    ["name_en" => "Turaib", "name_ar" => "طريب"],
    ["name_en" => "Turaif", "name_ar" => "طريف"],
    ["name_en" => "Turbah", "name_ar" => "تربة"],
    ["name_en" => "Tuwaim", "name_ar" => "تويم"],
    ["name_en" => "Udhaliyah", "name_ar" => "العضيلية"],
    ["name_en" => "Um Aljamajim", "name_ar" => "أم الجماجم"],
    ["name_en" => "Um Saad", "name_ar" => "أم سعد"],
    ["name_en" => "Umluj", "name_ar" => "أملج"],
    ["name_en" => "Umm Aldoom", "name_ar" => "أم الدوم"],
    ["name_en" => "Umm Hazim", "name_ar" => "أم حازم"],
    ["name_en" => "Unayzah", "name_ar" => "عنيزة"],
    ["name_en" => "Uqlat Al Suqur", "name_ar" => "عقلة الصقور"],
    ["name_en" => "Urayrah", "name_ar" => "عريره"],
    ["name_en" => "Ushaiqer", "name_ar" => "أشيقر"],
    ["name_en" => "Ushyrah", "name_ar" => "عشيرة"],
    ["name_en" => "Utayiq", "name_ar" => "عتايق"],
    ["name_en" => "Uthal", "name_ar" => "أثال"],
    ["name_en" => "Uthmaniyah", "name_ar" => "عثمانية"],
    ["name_en" => "Uyun", "name_ar" => "عيون"],
    ["name_en" => "Uyun Al Jiwa", "name_ar" => "عيون الجواء"],
    ["name_en" => "Waaer", "name_ar" => "واعر"],
    ["name_en" => "Wadeien", "name_ar" => "واديين"],
    ["name_en" => "Wadi Al Fora'a\t", "name_ar" => "وادي الفارع"],
    ["name_en" => "Wadi Bishah", "name_ar" => "وادي بيشة"],
    ["name_en" => "Wadi El Dwaser", "name_ar" => "وادي الدواسر"],
    ["name_en" => "Wadi Faraah", "name_ar" => "وادي فرا"],
    ["name_en" => "Wadi Fatimah", "name_ar" => "وادي فاطيمة"],
    ["name_en" => "Wadi Fatmah", "name_ar" => "وادي فاطمة"],
    ["name_en" => "Wadi Hali", "name_ar" => "وادي حلي"],
    ["name_en" => "Wadi Ibn Hashbal", "name_ar" => "وادي بن هشبل"],
    ["name_en" => "Wadi Numan", "name_ar" => "وادي نعمان"],
    ["name_en" => "Wadi Reem", "name_ar" => "وادي ريم"],
    ["name_en" => "Walyal Ahd Dist.", "name_ar" => "حي ولي العهد"],
    ["name_en" => "Yadamah", "name_ar" => "يدمة"],
    ["name_en" => "Yanbu", "name_ar" => "ينبع"],
    ["name_en" => "Yanbu Al Baher", "name_ar" => "ينبع البحر"],
    ["name_en" => "Yanbu Al Nakhal", "name_ar" => "ينبع النخل"],
    ["name_en" => "Yuthma", "name_ar" => "يثما"],
    ["name_en" => "Zalal", "name_ar" => "زلل"],
    ["name_en" => "Zalom", "name_ar" => "ظلوم"],
    // ["name_en" => "Zulfi", "name_ar" => "الزلفي"]
];

foreach ($cities as $city) {
    City::create($city);
}
    }
}
